version: '3'
services: 
  zoo1: 
    image: va-zk
    ports:
      - 2181:2181
    env_file: ./env
    environment:
      ZOO_MY_ID: 1

  zoo2:
    image: va-zk
    ports:
      - 2182:2181
    env_file: ./env
    environment: 
      ZOO_MY_ID: 2

  zoo3:
    image: va-zk
    ports:
      - 2183:2181
    env_file: ./env
    environment:
      ZOO_MY_ID: 3

  neo:
    image: va-neo
    ports: 
      - 7474:7474
      - 7687:7687
    env_file: ./env

  manager: 
    image: va-manager
    volumes:
      - ~/workspace/va/volume-analytics:/va
    ports: 
      - 8883:8443
      - 8888:8080
    env_file: ./env

  streams:
    image: va-streams
    ports:
      - 8989:8080
    volumes:
      - ~/workspace/va/cre:/code
      - ~/workspace/va/volume-analytics:/va
    env_file: ./env
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - neo

  vmysql:
    image: va-mysql
    ports: 
      - 3306:3306
    env_file: ./env

  gateway:
    image: va-gateway
    volumes:
      - ~/workspace/va/volume-analytics:/va
    ports:
      - 9090:8080
      - 9443:8443
    env_file: ./env

  webapp:
    image: va-webapp
    ports:
      - 9009:9001
    volumes:
      - ~/workspace/va/cre:/code
    env_file: ./env
